#ccflags-y += -Wall

ccflags-y += -I$(srctree)/drivers/devkit/tpkit

obj-y += \
	mstar_main.o \
	mstar_apknode.o \
	mstar_update.o \
	mstar_dts.o \
	mp_test/mp_command.o \
	mp_test/mp_entry.o \
	mp_test/mp_open.o \
	mp_test/mp_short.o \
	mp_test/mp_result.o \
	mp_test/mp_new_flow.o \


